# Generated by Django 4.2.15 on 2025-03-13 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0008_project_allow_member_to_create_label_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="discrepancy_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="project",
            name="discrepancy_percentage",
            field=models.IntegerField(default=80),
        ),
    ]
