# Generated by Django 4.2.15 on 2025-03-18 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0009_project_discrepancy_active_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="discrepancy_percentage",
        ),
    ]
