# Generated by Django 4.2.15 on 2025-03-18 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0010_remove_project_discrepancy_percentage"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="discrepancy_percentage",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="project",
            name="discrepancy_active",
            field=models.BooleanField(),
        ),
    ]
