# Generated by Django 4.2.15 on 2025-03-29 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0012_perspective_perspectivemember"),
    ]

    operations = [
        migrations.AddField(
            model_name="perspective",
            name="options",
            field=models.CharField(blank=True, default="", max_length=1024),
        ),
        migrations.AlterField(
            model_name="perspective",
            name="type",
            field=models.CharField(
                choices=[("number", "Number"), ("string", "String"), ("yes/no", "Yes/No"), ("options", "Options")],
                max_length=10,
            ),
        ),
    ]
