# Generated by Django 4.2.15 on 2025-03-30 00:00

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings

class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0013_perspective_options_alter_perspective_type"),  # ou outro último ficheiro da tua app
    ]

    operations = [
        migrations.CreateModel(
            name="ManualDiscrepancy",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.TextField()),
                ("label_counts", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("example", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="examples.Example")),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="projects.project")),
                ("reported_by", models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, null=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]