# Generated by Django 4.2.15 on 2025-04-01 01:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("examples", "0008_assignment"),
        ("projects", "0014_create_manualdiscrepancy"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="manualdiscrepancy",
            name="label_counts",
        ),
        migrations.AddField(
            model_name="manualdiscrepancy",
            name="status",
            field=models.CharField(
                choices=[("unresolved", "Unresolved"), ("resolved", "Resolved")], default="unresolved", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="manualdiscrepancy",
            name="example",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="manual_discrepancies", to="examples.example"
            ),
        ),
        migrations.AlterField(
            model_name="manualdiscrepancy",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="manualdiscrepancy",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="manual_discrepancies", to="projects.project"
            ),
        ),
        migrations.AlterField(
            model_name="manualdiscrepancy",
            name="reported_by",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.CreateModel(
            name="DiscrepancyLabelStat",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("label_text", models.CharField(max_length=255)),
                ("vote_count", models.IntegerField()),
                ("percentage", models.FloatField()),
                (
                    "discrepancy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="label_stats",
                        to="projects.manualdiscrepancy",
                    ),
                ),
            ],
        ),
    ]
