# Generated by Django 4.2.15 on 2025-04-06 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0017_alter_manualdiscrepancy_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="PerspectiveProject",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name="manualdiscrepancy",
            name="status",
            field=models.CharField(
                choices=[("unsolved", "Unsolved"), ("solved", "Solved")], default="unsolved", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="perspective",
            name="perspective_project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="perspectives",
                to="projects.perspectiveproject",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="perspective_associated",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects",
                to="projects.perspectiveproject",
            ),
        ),
    ]
