# Generated by Django 4.2.15 on 2025-04-06 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0018_perspectiveproject_alter_manualdiscrepancy_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="perspective",
            name="project",
        ),
    ]
