# Generated by Django 4.2.15 on 2025-04-24 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0019_remove_perspective_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="closed",
            field=models.BooleanField(default=False),
        ),
    ]
