# Generated by Django 4.2.15 on 2025-04-25 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0022_rulevote"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="can_view_rules_in_closed_project",
            field=models.BooleanField(default=False),
        ),
    ]
