# Generated by Django 4.2.15 on 2025-04-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0022_rulevote"),
    ]

    operations = [
        migrations.AddField(
            model_name="rule",
            name="voting_closed",
            field=models.BooleanField(default=False),
        ),
    ] 