# Generated by Django 4.2.15 on 2025-04-25 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0023_project_can_view_rules_in_closed_project"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="can_view_rules_in_closed_project",
        ),
    ]
