# Generated by Django 4.2.15 on 2025-04-26 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0024_remove_project_can_view_rules_in_closed_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="is_current_version",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="project",
            name="original_project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="versions",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="version",
            field=models.IntegerField(default=1),
        ),
    ]
