# Generated by Django 4.2.15 on 2025-04-29 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0020_discussion_discussionmessage"),
        ("projects", "0025_project_is_current_version_project_original_project_and_more"),
    ]

    operations = []
