# Generated by Django 4.2.15 on 2025-04-29 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0026_merge_20250429_1705"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="rule",
            unique_together={("project", "description"), ("project", "name")},
        ),
    ]
