# Generated by Django 4.2.15 on 2025-04-29 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0026_merge_20250429_1705"),
    ]

    operations = [
        migrations.AddField(
            model_name="discussion",
            name="project_version",
            field=models.IntegerField(default=1, help_text="Version of the project when the discussion was created"),
        ),
    ]
