# Generated by Django 4.2.15 on 2025-04-29 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0027_discussion_project_version"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discussion",
            name="project_version",
            field=models.IntegerField(help_text="Version of the project when the discussion was created"),
        ),
    ]
