# Generated by Django 4.2.15 on 2025-04-30 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0023_add_voting_closed_to_rule")
    ]

    operations = []
