# Generated by Django 4.2.15 on 2025-06-12 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0028_alter_discussion_project_version"),
        ("projects", "0029_merge_20250430_0231"),
    ]

    operations = []
