# Generated by Django 4.2.15 on 2025-06-14 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0027_alter_rule_unique_together"),
        ("projects", "0030_merge_20250612_2032"),
    ]

    operations = []
