# Generated by Django 4.2.15 on 2025-06-14 22:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0030_merge_20250612_2032"),
    ]

    operations = [
        migrations.AddField(
            model_name="perspectiveproject",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
