# Generated by Django 4.2.15 on 2025-06-14 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0031_merge_20250614_2139"),
    ]

    operations = [
        migrations.AddField(
            model_name="rule",
            name="version",
            field=models.IntegerField(default=1),
        ),
    ]
