# Generated by Django 4.2.15 on 2025-06-14 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0031_perspectiveproject_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="perspectiveproject",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
