# Generated by Django 4.2.15 on 2025-06-14 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0032_rule_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="rule",
            name="voting_deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
