# Generated by Django 4.2.15 on 2025-06-14 22:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0032_perspectiveproject_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="perspectiveproject",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_perspective_projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
