# Generated by Django 4.2.15 on 2025-06-15 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0033_add_voting_deadline_to_rule"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rule",
            name="voting_deadline",
        ),
    ]
