# Generated by Django 4.2.15 on 2025-06-15 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0034_remove_rule_voting_deadline"),
    ]

    operations = [
        migrations.AddField(
            model_name="rule",
            name="voting_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rule",
            name="voting_end_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
