# Generated by Django 4.2.15 on 2025-06-15 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0033_perspectiveproject_created_by"),
        ("projects", "0035_rule_voting_end_date_rule_voting_end_time"),
    ]

    operations = []
