# Generated by Django 4.2.15 on 2025-06-15 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0036_merge_20250615_1707"),
        ("projects", "0036_merge_20250615_2028"),
    ]

    operations = []
